### ISSUE TITLE
action - build a oneoff image on pull requests

### ISSUE THREAD

**Issue by castrojo** [ublue-os/base#14]
Currently the image just gets built when a PR is opened. 

For workflow we'll want PRs to build an image when someone submits a fix so we can test it, and then build the image after the PR is merged.

**Comment by p5** [comment]
When new PRs are created or updated, should the image be tagged pushed to GHCR?  Or are you only wanting to test if they build successfully?

**Comment by castrojo** [comment]
Yeah having a tag-per-pr fixed this, just forgot to close.
