### ISSUE TITLE
recipe.yml flatpaks do not install and issues with LibreOffice install via yafti.yml 

### ISSUE THREAD

**Issue by simon-truhter** [ublue-os/base#140]
https://github.com/simon-truhter/personal-ublue/commit/592f12d3921f967291ec81894a8b823f12d12aba

> These Flatpaks (from flathub) will be available for install on boot
> this is just an example selection.

So its not about adding them directly into the image? 

i tried adding the default values again but it does not work at all (for me) i dont know what im doing wrong,
since flatpaks in the yafti.yml just works in the post install. but also in the post install script it failed to install LibreOffice.
Everything else was installed fine.  I tried to install it via the terminal and it worked fine, so sadly i cant tell you currently what the issue is. 

**update regarding yafti.yml**
i now realized looking to the new group of yafti.yml flatpak apps that some are even when its default is true
some of them seem to be for no obvious reason to be not selected. i guess this comes from  this entries which are duplicates from other sections where default option is false.  (i dont think this is intended behavior, maybe it is)

i would prefer that i can add flatpaks to be installed directly and do not have to do it in the post install
so going with yafti.yml for now seems to be the only option.

**Comment by simon-truhter** [comment]
i still dont dig the recipe.yml section , whats reasonable purpose does it fullfil @castrojo ?

**Comment by castrojo** [comment]
There's no current way for us to preinstall flatpaks, the only way is in a post boot script like yafti.

**Comment by simon-truhter** [comment]
Thanks for the info

**Comment by EinoHR** [comment]
> i still dont dig the recipe.yml flatpak section , whats reasonable purpose does it fullfil @castrojo ?

It existed before yafti was used, when it was the only place the flatpaks were added to. Then when switching to yafti, I kept it around for ease of use, but you can totally not use it and edit the yafti.yml instead.

Also, this is the base repo, whereas your custom repo is based on startingpoint, for further issues, please add them to the right repository.
