### ISSUE TITLE
chore: actions is building images on readme PRs

### ISSUE THREAD

**Issue by castrojo** [ublue-os/base#50]
The action is only ignoring readme edits when we merge, we need to set that to PRs as well so we're not kicking off image builds when editing readmes and other text files.

This needs to apply for PRs and merges.

**Comment by animeshn99** [comment]
@castrojo , Please assign me. I am raising PR right now. Feel free to directly assign me in any devops issues

**Comment by animeshn99** [comment]
Thanks @marcoceppi

**Comment by animeshn99** [comment]
sorry this is my first time.. i did got how to open the PR with this issue tag.. the PR is now opened  at https://github.com/ublue-os/base/pull/63

**Comment by animeshn99** [comment]
#63

**Comment by castrojo** [comment]
Thanks!
