### ISSUE TITLE
Implement versioning of each release

### ISSUE THREAD

**Issue by castrojo** [ublue-os/base#6]
People should be able to do `base:37`, `base:38`, and so on, and then we should make sure `:latest` points to the latest stable release, that way if you want to replicate a rolling release you follow latest, but you can also pin to a specific major version.

**Comment by castrojo** [comment]
I've added `37` to the latest images, however we'll need to figure out how to build/publish 37 and 38 at the same time. Once F38 hits beta I'll set up 38 builds.

**Comment by p5** [comment]
If you wanted each major version to use the same Containerfile, you could use 
```Dockerfile
ARG FEDORA_MAJOR_VERSION
```
and in GitHub Actions, create a matrix containing all different releases you want to build against.
When you call Buildah, pass through the version as a `build_args` parameter.

You can also tag the image based on the matrix too.

I'll try to make a draft PR soon
